### ISSUE TITLE
Ask before closing a Scratchpad.

### ISSUE THREAD

**Issue by Shuraen** [LadyDefile/Wordsmith-DalamudPlugin#19]
It would be nice to have a window asking if we want to close a Scratchpad.
I have either hit "Delete Pad" or hit "Close" from the Settings menu one too many times, losing all of my progress.

**Comment by LadyDefile** [comment]
I can definitely do this. Look forward to it in my next update!

**Comment by LadyDefile** [comment]
![image](https://user-images.githubusercontent.com/67084868/188787499-c2b5dcf2-ac56-4871-b33c-48736e3a0f95.png)
This will be going live in the testing version soon (probably tonight). This dialog should appear when using the "Delete Pad" button or the "Close" button from settings.
