### ISSUE TITLE
Wordsmith crashing client.

### ISSUE THREAD

**Issue by meenanox** [LadyDefile/Wordsmith-DalamudPlugin#20]
Hi there

Since 6.2 update of FFXIV, upon using scratchpad and entering the third paragraph my game client suddenly freezes and crashes with no error. I have tried a complete reinstall of dalamud - disabling all other plugins, checking game and repairing game, reinstalling wordsmith and such but all to the same avail.

I will write until paragraph three and the game will freeze, go nonresponsive and then crash once scratchpad has split the post into the third paragraph or enters the /3 area. 

I dont really know how to send a log, but if you can replicate this it would be great. It has happened to me 100% of the time regardless of device I am playig on (laptop or pc)

**Comment by LadyDefile** [comment]
Hmmm. I'll look into it. I can't check on it today though. Have you tried the latest, testing version?

**Comment by meenanox** [comment]
I am on the latest version.

**Comment by LadyDefile** [comment]
So, I was able to find time to test the issue. I can't seem to reproduce the problem and even went so far as type into the 4th chunk. 
![image](https://user-images.githubusercontent.com/67084868/190290135-7a497d63-aab6-48e6-98d3-9ba107ddc2cc.png)

Just to triple check to be safe, can you tell me the version number you have?

**Comment by meenanox** [comment]
I am using 1.5.1

I only run this, Mare, penumbra and even when disabling all those others - it still crashes. It's sometimes a bit random. Im not entirely sure why.

**Comment by meenanox** [comment]
It onyl crashes when im writing IN scratchpad, if i have wordsmith running but am writing in the game textbox, there is no issue.

**Comment by meenanox** [comment]
I. T  — Today at 15:23
my game just crashed mid emote
uuuugh

S.K — Today at 15:23
NOOOO
were you writing it in wordsmith?
or on the standard chat box
I've been having issues with wordsmith

I.T  — Today at 15:24
in wordsmith

S.K — Today at 15:24
yes mine crashes too in wordsmith

I.T — Today at 15:24
crashed to desktop without an error

====

My friend today is also having the same issue. Crashed with no error to pc screen.

**Comment by LadyDefile** [comment]
I'll have quite a bit more time to do testing today. Hopefully I'll be able to pinpoint the issue.

**Comment by LadyDefile** [comment]
I'm having quite a bit of trouble trying to replicate this issue. I've been at this for a few hours now and have yet to cause a crash (though some of what I've been doing has been just general code optimization/maintenance along the way). I have a few questions that might help narrow it down for me.

1. Are you typing fluidly when it crashes or are there pauses?
2. How frequent does the crash seem to happen?
3.  and your friend and is it always when you get into the third paragraph or is the number inconsistent?

In the meantime I'll keep digging around and seeing if I can replicate the issue or find any code that seems poorly written.

**Comment by meenanox** [comment]
We are typing fluidly, it always crashes mid type, with a frozen sccreen.
It probably happens each time I use the program. It can be anywhere beyond the third paragraph. I'm not entirely sure what is causing it entirely. But it has happened for more than just myself at this point.

**Comment by LadyDefile** [comment]
The odd thing about it crashing that way is that I have all of the essential code pieces tucked inside of a crash dump failsafe/reporting system so it *shouldn't* be able to just crash the entire game. Obviously, it is, which means something is going screwy. I'll keep poking around and see what I can find. In the meantime, I'm really sorry for the inconvenience it's causing with this crash and thank  you for being patient while I try to figure out what is going on.

**Comment by Vnella** [comment]
I would like to put in my 2 cents of what happens to me with this same issue. So any time i get to the third line i get crashed out of my game I don't understand why since there is no error message after the crash. in all 3 to 4 different times that it happened to me i was typing both fluidly and pausing at times since i had to remember what i was trying to type out the first time before the crash. It seems to only specifically when the 3 paragraph is hit sometimes very rarely though it will crash on the 1st or 2nd. However when it crashed on the 1st or 2nd paragraph that only happens if my game doesn't crash on the 3rd then it will crash a few seconds to a few minutes later.  At max no more than 5 minutes after typing a successful typing of the 3rd paragraph and sending of the 3 paragraph.

**Comment by Vnella** [comment]
When i say 3rd line I meant paragraph sorry about that.

**Comment by LadyDefile** [comment]
@Vnella Are you also using 1.5.x or are you one 1.4.x?

**Comment by Vnella** [comment]
> @Vnella Are you also using 1.5.x or are you on 1.4.x?

I am using 1.5.x

**Comment by LadyDefile** [comment]
Ok. At this point, it seems that this issue is prevalent only in the latest version. That should narrow down where the crash is happening. The biggest change to 1.5.x is the automatic spell checking in the background. That should narrow it down and, hopefully, lead to an *"Aha!"* moment.

**Comment by Vnella** [comment]
> Ok. At this point, it seems that this issue is prevalent only in the latest version. That should narrow down where the crash is happening. The biggest change to 1.5.x is the automatic spell checking in the background. That should narrow it down and, hopefully, lead to an _"Aha!"_ moment.

Just checking in to see if there is any fix to this issue yet

**Comment by LadyDefile** [comment]
I'm having trouble replicating the issue myself which is making it hard to come up with any real fix. Right now, I'm going through the code and optimizing a few things and changing the parts that I suspect *could* be involved in the crash but I'm not ready to publish the latest version just yet. I should have it out soon though. I have some free time tonight so I'll probably nose-to-grindstone it for a few hours.

**Comment by LadyDefile** [comment]
Judging solely on the fact that the issue is in the latest version, I suspect it has something to do with the automated spell checking that I implemented, which narrows it down slightly, but there is a lot involved in that process so there is no real way to be sure. I've got a couple cross-thread calls in there that could be the culprit so I'm currently working to remove those and make each thread independent of the other. If that doesn't fix it, I'll try just scheduling the spell check on the same thread.

**Comment by LadyDefile** [comment]
@meenanox @Vnella 
Could I ask you two to do a favor? Could you disable automatic spell checking in the settings for the time being. I'd like to see if not spellchecking fixes the issue for you.

**Comment by LadyDefile** [comment]
Nevermind. it appears that setting is broken at the moment.
I'm hoping to push a fix tonight for the bug but we'll see if it works or not, lol.

**Comment by LadyDefile** [comment]
I just pushed v1.5.2. It has a couple tweaks in it. If it still crashes for you after updating to v1.5.2, try disabling automatic spell checking and let me know if that resolves the crashing for you. I'm hoping that this update fixes the crashes all together but if not, that could be a way to narrow it down.

**Comment by meenanox** [comment]
I'll use it and see if it works!

**Comment by LadyDefile** [comment]
@meenanox Thank you! Be sure to let me know if you find anything acting weird.

**Comment by LadyDefile** [comment]
@meenanox I take it you've not had an issues to report in the last three days? No news is good news?

**Comment by LadyDefile** [comment]
Alright. Haven't heard anything about this still happening in the last week so I'm going to go ahead and mark this as closed for now.
