### ISSUE TITLE
Wordsmith crash/error

### ISSUE THREAD

**Issue by Nanu308** [LadyDefile/Wordsmith-DalamudPlugin#21]
Here is the logfile:

`
{"LastID":"1","NextID":"2","ID":"1","Namespace":"NULL","WindowName":"Wordsmith - Scratch Pad #1","IsFocused":"True","RespectCloseHotkey":"True","Position":"NULL","PositionCondition":"None","Size":"NULL","SizeCondition":"None","SizeConstraints":"Dalamud.Interface.Windowing.Window\u002BWindowSizeConstraints","Collapsed":"NULL","CollapsedCondition":"None","Flags":"NoScrollbar, NoScrollWithMouse, MenuBar","ForceMainWindow":"False","BgAlpha":"NULL","ShowCloseButton":"True","IsOpen":"True","\u003CID\u003Ek__BackingField":"1","_lastState":"{ ChatType: None, ScratchText: \u0022Claymore looked up at the sky as he walked and dragged \u0022, UseOOC: False, TellTarget: \u0022\u0022, CrossWorld: False, Linkshell: 0 }","_preserveCorrections":"False","_corrections":"{ \u0022\u0022 }","_errors":"{ \u0022\u0022 }","_notices":"{ \u0022\u0022 }","_spellChecked":"False","_chatType":"None","_header_parse":"True","_telltarget":"","_linkshell":"0","_crossWorld":"False","_scratch":"Claymore looked up at the sky as he walked and dragged ","_scratchBufferSize":"4096","_useOOC":"False","_chunks":"{ \u0022{ StartIndex: 0, Header: \u0022\u0022, Text: \u0022Claymore looked up at the sky as he walked and dragged\u0022, Words: Wordsmith.Data.Word[], Marker: , OOC Start: \u0022\u0022, OOC End: \u0022\u0022 }\u0022 }","_nextChunk":"0","_canUndo":"False","_editorstate":"0","_textchanged":"False","_text_history":"{ \u0022\u0022 }","_lastWidth":"600","_ignoreTextEdit":"False","_replaceText":"","_cancellationTokenSource":"System.Threading.CancellationTokenSource","_spellchecktimer":"System.Timers.Timer","_selected_history":"-1","_nextID":"3","Exception":{"Error":"System.InvalidOperationException: Collection was modified; enumeration operation may not execute.\r\n   at Wordsmith.Gui.ScratchPadUI.DrawAlerts() in /work/repo/Wordsmith/Gui/ScratchPadUI.cs:line 525\r\n   at Wordsmith.Gui.ScratchPadUI.Draw() in /work/repo/Wordsmith/Gui/ScratchPadUI.cs:line 241","Message":"Collection was modified; enumeration operation may not execute."}}
`

**Comment by LadyDefile** [comment]
Thank you for posting this. The issue that caused this is actually already resolved in the test version and that update should be live soon. It's safe to ignore this message when it pops up though. It's not super important.
