### ISSUE TITLE
Buttons at bottom of scratchpad are cut off

### ISSUE THREAD

**Issue by lyrayesterday** [LadyDefile/Wordsmith-DalamudPlugin#27]
The context buttons at the bottom of the scratchpad window are partially outside of the window. This issue persists after resizing the scratchpad.

![image](https://user-images.githubusercontent.com/76705291/204097451-8efdbbc0-636c-456a-ade5-34fded943b82.png)

**Comment by LadyDefile** [comment]
Thank you. Do you happen to know what your UI scale is so I can test things on my end?

**Comment by lyrayesterday** [comment]
Dalamud is scaled to 14pt font.
![image](https://user-images.githubusercontent.com/76705291/204136843-ddcc6851-dc77-437f-8dba-a0456c1ed4b0.png)

**Comment by LadyDefile** [comment]
Thank you so much for bringing this to my attention. Good news, I found the problem. It was a minor calculation issue in the frame size for displaying text chunks. I've got one other bug to pay attention to and then I should (hopefully) be able to push the update and fix the button problem.
