### ISSUE TITLE
Spellcheck broken

### ISSUE THREAD

**Issue by BartlamKevin** [LadyDefile/Wordsmith-DalamudPlugin#28]
I have removed and reinstalled the plugin multiple times even removing the config and keeps saying: Failed to load dictionary web:lang_en Spell check disabled.

There are no disctionary files in the manifest or {C:\Users\username\AppData\Roaming\XIVLauncher\installedPlugins\Wordsmith\1.7.2\Dictionaries

There isn't even a Dictionaries folder

**Comment by LadyDefile** [comment]
Hi! Thanks for taking the time to write about the issue. So, I did notice this issue before. The "Dictionaries" folder is a folder you can add to use custom dictionaries as of Wordsmith 1.7.0. The manifest is a just a file that tells Wordsmith what dictionaries are currently available in my online repo. Unfortunately, I made a bit of a big mistake when moving to using this online repo; I didn't account for HTML 304 responses and so it fails unfortunately often.

I've already patched this issue and it's much, much more reliable at loading the dictionaries now (as of v1.7.3) but, unfortunately, I can't just push the version out, I have to wait for the Dalamud team to approve my changes (they take security very seriously after all). I'm hoping that they get it out to you soon though and I'm super sorry for the mistake. 

If you're curious, this is the PR I'm waiting for the Dalamud team to approve. https://github.com/goatcorp/DalamudPluginsD17/pull/800

You can see the patch notes there if you want to take a peak. Again, super sorry that this happened. Hopefully the new version is live by morning.
