### ISSUE TITLE
Wordsmith crashing the game.

### ISSUE THREAD

**Issue by Kamentine** [LadyDefile/Wordsmith-DalamudPlugin#32]
My friends and I have been struggling with the Wordsmith program abruptly crashing us midway through writing our posts.
![wut](https://user-images.githubusercontent.com/120316486/206905758-1c013a89-a355-490c-8937-21fa1c51e290.png)

**Comment by LadyDefile** [comment]
You say this happens in the middle of writing your posts? I'll take a look and as if I can't figure out why. Thanks for telling me about this!

**Comment by LadyDefile** [comment]
The next time this issue happens, is there any chance you can grab the dalamud.log file for me?

**Comment by LadyDefile** [comment]
Oh, and if you could send me your Wordsmith.json config file as well.

**Comment by LadyDefile** [comment]
Since there hasn't been any updates on this in a week I'm marking the issue closed.
