### ISSUE TITLE
Using a custom marker prints out code

### ISSUE THREAD

**Issue by Dark-Cr0w** [LadyDefile/Wordsmith-DalamudPlugin#37]
Hi there! Firstly wanted to say thank you for adding this feature in but I found a bug when i tried to use it at first :c 

What I typed:
![image](https://user-images.githubusercontent.com/109322836/211186098-bc0deafc-0ef0-4b1b-8dba-1b95be4e5e93.png)
What it prints into the chat: [ not the :') ]
![image](https://user-images.githubusercontent.com/109322836/211186117-1e36d482-11ca-4f6e-81ba-8f8cdca66b71.png)
Current marks & tags options:
![image](https://user-images.githubusercontent.com/109322836/211186154-7592a1ac-bb8d-42af-972a-dceb3d4d8710.png)

I also tested with other markers- same thing just in the place where I set it for.

**Comment by LadyDefile** [comment]
Well damn. That is definitely not how that is supposed to work, lol. It seems I accidentally used a 'ToString()' call somewhere. I'll take a look at this and should have it patched up in the next couple hours. Just about to have my coffee.

**Comment by LadyDefile** [comment]
Seems I have another thing to add to my QA checklist.

**Comment by LadyDefile** [comment]
I found the problem and I was correct. Where I gather together the markers to be copied to clipboard I apparently had it converting the object via `ToString()` which was definitely wrong, lol. It's fixed and I'll send this update to Dalamud as soon as I run my QA list over it (including the new check to ensure everything copies properly, lol.)

**Comment by LadyDefile** [comment]
https://github.com/goatcorp/DalamudPluginsD17/pull/922

A fix is on the way! Once the Dalamud team gets around to approving this update this should be fixed along with several other bugs I managed to find today. The patch notes for the coming update are in the link I provided.
