### ISSUE TITLE
Spell check not working even when on

### ISSUE THREAD

**Issue by Riot1138** [LadyDefile/Wordsmith-DalamudPlugin#38]
Whenever I open a new scratchpad the automatic spell-check isn't working. I have to open the spell check settings, even with it ticked on and hit Apply for the spell checker to work.
**Make a new scratchpad with a clear spelling error:**
![image](https://user-images.githubusercontent.com/123217321/216797808-9b4092fe-138f-4fd4-b803-e3caec669e9e.png)
**It is ticked to be on:**
![image](https://user-images.githubusercontent.com/123217321/216797812-66d6f964-dfbe-4f39-a0af-5a461417e1f7.png)

**After hitting apply:**
![image](https://user-images.githubusercontent.com/123217321/216797818-36092adb-b7fb-45d7-b58d-7255859b5fde.png)

**Comment by LadyDefile** [comment]
Hi there. Sorry it took a couple days to respond, had a few other things I was working on.
1. Does this happen every time you reboot the game?
2. This is after you open every new scratch pad, even after fixing the previous one? (i.e. fixed for pad 1, opened pad 2, had to fix again)
3. Can you post your configuration file, please? It's at `%appdata%\XIVLauncher\pluginConfigs\Wordsmith.json`

**Comment by LadyDefile** [comment]
As luck would have it, I actually believe I found the issue by pure luck and it's kind of a funny one. I accidentally wrapped one extra line inside of a `#if DEBUG` wrapper which caused the spellcheck to work fine with debug builds (a.k.a developer builds) but as soon as it was compiled for giving to everyone else, it would break.

**Comment by Riot1138** [comment]
Oh nice! Good to hear. Thank you 😀.  I'll double check when I'm home!
