### ISSUE TITLE
[Suggestion] Word usage tracking

### ISSUE THREAD

**Issue by GuppyLaxx** [LadyDefile/Wordsmith-DalamudPlugin#41]
Something to nudge you in the right direction if you keep using the same words over and over. **No need to replace words, or even have fancy tracking like nouns, adjectives, verbs, etc, or word variations like past, present, future.** 

Whenever you hit **"Copy**", you could grab each word used and make a list, while keeping track of usage. Makes it easier to balance out how much you use certain words if you have *some* metric for it. Making it per-scratchpad might be the best option, along with a separate option to clear out the tracker in that specific scratchpad.

I know I'm terribly guilty of writing the same words over and over, SPECIALLY amongst multiple "emotes" and having to scroll up to read back on what I've wrote just to make sure I'm not a broken record gets a bit... _Annoying._ If I could look at the side of my scratch pad, in a separate window maybe, and see something like...
```
- As 30
- He 23
- is 20
- Leant 15
- Grabbed 10
- Hugged 4
... etc
```
Would help me balance out the words I use a LOT when it comes to repeating certain actions happening at once, or a reminder of something done before, and so on.
Maybe an option to make it sort by Ascending, Descending, Alphabetical too?

**Comment by LadyDefile** [comment]
Wow, I just now saw this. Sorry that took so long. I've been busy with Starfield and apparently missed the email about it.
I can look into something like this but my concern is the potential memory footprint. I don't think it would use all that much but I can't make any promises until I do some research into it.

**Comment by GuppyLaxx** [comment]
No worries!
I can see how it could become a memory issue, though I feel that would only happen with enough variations of words and so on. Specially if the tracking is particularly sensitive!
I'm not too experienced on making stuff for FF14 but regardless I appreciate you looking at this at all!

**Comment by LadyDefile** [comment]
![image](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/67084868/73826dad-70cf-4f7c-ab8f-d9af9055407c)

![image](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/67084868/85b63742-2f61-41d0-b139-307c59748bd9)

**Comment by GuppyLaxx** [comment]
Awesome! Exactly what I imagined haha
